name: "S3 Stage Deploy Action"
description: "Deploys code of your choice to AWS S3 separated by branch name"
inputs:
  s3-bucket:
    description: "S3 Bucket name"
    required: true
  secret-access-key:
    description: "AWS Secret Access Key"
    required: true
  access-key-id:
    description: "Access Key Id"
    required: true
outputs:
  s3_url: # id of output
    description: "URL of the deployed content"
runs:
  # using: "node12"
  # main: "index.js"
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.s3-bucket }}
    - ${{ inputs.secret-access-key }}
    - ${{ inputs.access-key-id }}
